### ISSUE TITLE
Fix flash-after-verify in Etcher integration

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io-modules/etcher-sdk#12] opened 2018-07-16 12:42 UTC

**Comment by curcuz** [comment] 2018-08-28 12:58
@jhermsmeier we need precise instructions on how to reproduce - neither me nor @zvin were able to do so far

**Comment by jhermsmeier** [comment] 2018-08-28 13:31
@curcuz this happened just when flashing more than one card, with auto-unmount turned off

**Comment by zvin** [comment] 2018-09-06 09:41
I'm not sure this is specific to the `etcher-sdk` branch of etcher in etcher pro.

**Comment by zvin** [comment] 2018-09-06 12:33
This is due to an issue in `sudo-prompt`.
PR opened on `sudo-prompt` and `etcher`.
 * https://github.com/jorangreef/sudo-prompt/pull/76
 * https://github.com/resin-io/etcher/pull/2469
Closing this.

**Closed by zvin** 2018-09-06 12:33 UTC
Labels: cant-reproduce, etcher-integration, linux, priority:high
